[mongodb]
mongodb-dev.bunnyone.online

[catalogue]
catalogue-dev.bunnyone.online 

[redis]
redis-dev.bunnyone.online

[user]
user-dev.bunnyone.online

[all:vars]
ansible_user=ec2-user 
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.bunnyone.online
USER_HOST=user-dev.bunnyone.online
REDIS_HOST=redis-dev.bunnyone.online
CART_HOST=cart-dev.bunnyone.online





