[mongodb]
mongodb-dev.bunnyone.online

[catalogue]
catalogue-dev.bunnyone.online 

[redis]
redis-dev.bunnyone.online

[user]
user-dev.bunnyone.online

[cart]
cart-dev.bunnyone.online

[mysql]
mysql-dev.bunnyone.online

[shipping]
shipping-dev.bunnyone.online

[rabbitmq]
rabbitmq-dev.bunnyone.online

[payment]
rabbitmq-dev.bunnyone.online

[frontend]
frontend-dev.bunnyone.online


[all:vars]
ansible_user=ec2-user 
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.bunnyone.online
USER_HOST=user-dev.bunnyone.online
REDIS_HOST=redis-dev.bunnyone.online
CART_HOST=cart-dev.bunnyone.online
CATALOGUE_HOST=catalogue-dev.bunnyone.online
FRONTEND_HOST=frontend-dev.bunnyone.online
PAYMENT_HOST=payment-dev.bunnyone.online
RABBITMQ_HOST=rabbitmq-dev.bunnyone.online
SHIPPING_HOST=shipping-dev.bunnyone.online
MYSQL_HOST=mysql-dev.bunnyone.online

